### ISSUE TITLE
EPFL

### ISSUE THREAD

**Issue by konstmish** [Naereen/ama#1]
Hey!
I came across your webpage and found that you did your internship at EPFL. Why didn't you go there for a phd? Did you change your mind while interning there?

**Comment by Naereen** [comment]
Hi,

Indeed, I preferred to do my PhD in France (partly [there](http://www.rennes.supelec.fr/ren/rd/scee/membres.html) and [there](https://team.inria.fr/sequel/team-members/)).
- EPFL has nothing to do with it, it would have been the best place on Earth to do a PhD :sparkles: :+1: !
- But as I am a (future) professor of maths & computer science, in France, with [a special status](https://en.wikipedia.org/wiki/Agr%C3%A9gation_in_France#Secondary_education) (see the 6th paragraph about *preparatory classes to the "grandes écoles"*), and it was more interesting [to teach in France](http://perso.crans.org/besson/teaching.en.html#in-2016-2017) during my PhD than to teach in a foreign country and risk to loose this special status by doing a 4 years PhD (as it is at EPFL). I am aiming at a teaching position in a *preparatory class to the "grandes écoles"* and preferred the more cautious option.
- I also wanted to change the subject from my internship to my PhD.

**Comment by konstmish** [comment]
I got interested by this lab and it seems to be a great place for a phd, but I'm concerned by what I will be able to do afterwards. And the topic I'm thinking of working on is pretty much the same as the one in your report. Do you think it's a promising subject for research?

**Comment by Naereen** [comment]
I would suggest that you contact them rather than me.
