### ISSUE TITLE
Sir, I was going through you algo bandits project and I truly appreciate your work on it. But I found the the DMC file missing(of 0KB) in the policies multiplayer folder, the file is for dynamic number of users. My request is if you can help me with sending or uploading the file it would be a massive help for my project. I have taken your project for my graduation and trying to sample the arms which are refrained in the MEGA algorithm. Cant find an emo here but a lot of love for you : )

### ISSUE THREAD

**Issue by pratayaa** [Naereen/ama#2]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Naereen/)! [I](https://github.com/Naereen/) will try my best to answer to you and help you!

- [ ] Check that your question [was not already answered](https://github.com/Naereen/ama/issues?q=is%3Aissue+is%3Aclosed) please.

> Note : si vous parlez français, vous pouvez utiliser [mon dépôt "demandez-moi n'importe quoi"](https://github.com/Naereen/ama.fr/issues/new) (in French :fr:).

**Comment by Naereen** [comment]
Hi,
That's not a bug, I simply haven't implemented the Dynamic Musical Chair algorithm yet.
I won't try, as I don't need right now to support dynamic multi-players simulations, sorry.

If you write it, please feel free to [submit a pull request](https://help.github.com/articles/creating-a-pull-request/) on [SMPyBandits](https://github.com/SMPyBandits/SMPyBandits/pulls), and I'll test your implementation and maybe merge.

Regards
