### ISSUE TITLE
Sir, I am not able to visualize how to change value of nbArms dynamically(in AlgoBandits project). Don’t know where to make changes in mega code. Please tell us where to put our efforts.  Kindly assist, we guys need your help.

### ISSUE THREAD

**Issue by pratayaa** [Naereen/ama#3]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Naereen/)! [I](https://github.com/Naereen/) will try my best to answer to you and help you!

- [ ] Check that your question [was not already answered](https://github.com/Naereen/ama/issues?q=is%3Aissue+is%3Aclosed) please.

> Note : si vous parlez français, vous pouvez utiliser [mon dépôt "demandez-moi n'importe quoi"](https://github.com/Naereen/ama.fr/issues/new) (in French :fr:).

**Comment by Naereen** [comment]
Euh hi,

First of all, please stop using this repo for your issues: they should be opened [directly on the SMPyBandits](https://github.com/SMPyBandits/SMPyBandits/issues/new) project.
Second of all, your question should go inside the text of the issue, not in 5 lines in the title. (please)

Regarding this question, I didn't implement any form of support of problems with a varying number of arms in SMPyBandits.
I don't and won't have time to do it, so regarding your goal, either you implement it yourself in SMPyBandits, then submit a pull request when it will be done (cleanly) and if it works, either I forget about it.

Please open a new issue on [SMPyBandits](https://github.com/SMPyBandits/SMPyBandits/issues/new) and I will indicate there what should be changed to support problems with a varying number of arms.
Disclaimer: it won't be easy! it requires a serious change in the entire project APIs…
