### ISSUE TITLE
Can I make a similar repo? I'll give the credits to you.

### ISSUE THREAD

**Issue by MadhavBahl** [Naereen/ama#4]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Naereen/)! [I](https://github.com/Naereen/) will try my best to answer to you and help you!

- [x] Check that your question [was not already answered](https://github.com/Naereen/ama/issues?q=is%3Aissue+is%3Aclosed) please.

> Note : si vous parlez français, vous pouvez utiliser [mon dépôt "demandez-moi n'importe quoi"](https://github.com/Naereen/ama.fr/issues/new) (in French :fr:).

**Comment by Naereen** [comment]
Hi @MadhavBahlMD, yes of course you can.

This repository is open-source, under [the MIT license](https://lbesson.mit-license.org/), as [stated here](https://github.com/Naereen/ama#scroll-license--).
It will take about 2 minutes for you to do a similar repository:
1. Click the "fork" button on my repository,
2. Edit the README.md file to change the names, links etc. Change the text to suit your need.
3. And that's it!

Don't hesitate to ask for help if needed. No need to give credits to me, don't worry.

**Comment by MadhavBahl** [comment]
Alright, thanks @Naereen :smiley:
