### ISSUE TITLE
Store Private Key

### ISSUE THREAD

**Issue by mikeelton0** [Naereen/ama#6]
## New issue :boom: !

Thank you for your interest in [my projects](https://github.com/Naereen/)! [I](https://github.com/Naereen/) will try my best to answer to you and help you!

- [ ] Check that your question [was not already answered](https://github.com/Naereen/ama/issues?q=is%3Aissue+is%3Aclosed) please.

> Note : si vous parlez français, vous pouvez utiliser [mon dépôt "demandez-moi n'importe quoi"](https://github.com/Naereen/ama.fr/issues/new) (in French :fr:).

I would like to know how where found keys are stored ? and also have you been able to see any address with balance yourself?

Thank you

**Comment by Naereen** [comment]
Hello @mikeelton0 and thanks for your question.
I don't understand what are you asking, could you please develop your question and explain more in details? Thanks!
Regards.
@Naereen
