### ISSUE TITLE
How to implement the C&P algorithm from arXiv:1902.08036

### ISSUE THREAD

**Issue by DPearson006** [Naereen/ama#7]
## New issue :boom: !

Dear Sir,

  I'm a student from Sun Yat-sen University, China. I am learning about MAB algorithm and I recently read the paper [Multi-Player Bandits: The Adversarial Case, by Pragnya Alatur, Kfir Y. Levy, Andreas Krause, arXiv:1902.08036]. I'm just getting started and I'm not capable of implementing the C&P algorithm from the paper. I discovered that you have opened an issue on 28 Feb 2019 relating to this problem (https://github.com/SMPyBandits/SMPyBandits/issues/184#issue-415680398). If you could help in publishing the code on your github so that I can learn from it, it would be a great help. 

Sincerely yours,
Pu Deng.

**Comment by Naereen** [comment]
Hello @DPearson006,
As you can see in the issue you mentioned, I opened it more than three years ago, and have not closed it. I finished my PhD thesis, and SMPyBandits was part of this work.
I no longer have the time to work on bandit algorithms and this library, unfortunately (I'm now teaching full time).
I cannot help you regarding this C&P algorithm, sorry.
Regards,
@Naereen

**Comment by DPearson006** [comment]
Dear Sir,

I see. I think I'll try to get some inspiration from your other code. Thank you for your reply and your work!

Sincerely yours,
Pu Deng.
